name: PHP analyze & tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP 7.4
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4

    - uses: actions/checkout@master

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@master
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run static analyze - phplint, phpstan, psalm.
      run: composer php-analyze

    - name: Run PHPUnit Tests
      run: composer tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@main
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}