name: PHP analyze & tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Validate composer.json
      run: composer validate --strict

    - name: Prepare
      run: make docker-compose

    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@main
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}

    - name: Build
      run: make init

    - name: Run static php analyze.
      run: make php-analyze

    - name: Run PHPUnit Tests
      run: make php-tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@main
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}